apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybus-deploy
  labels:
    app: bus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mybus
  template:
    metadata:
      labels:
        app: bus
        service: mybus
    spec:
      containers:
        - name: mybus
          image: ananddocker18/mybus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: mybus
  labels:
    app: bus
    service: mybus
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    service: mybus
